version: "3"
services:
    user:
        image: skvist/docknode
        #build:
        #    context: .
        #    dockerfile: .docker/node-8.9/Dockerfile
        volumes:
            - ./services/users/:/home/node/app
        environment:
            - DBWEBB_PORT_1=${DBWEBB_PORT_1}
            - DBWEBB_DSN=${DBWEBB_DSN}
        ports:
            - "${DBWEBB_PORT_1}:${DBWEBB_PORT_1}"
        links:
            - mongodb
        command: "npm start"

    kanban:
        image: skvist/docknode
        # build:
        #    context: .
        #    dockerfile: .docker/node-8.9/Dockerfile
        volumes:
            - ./services/kanban/:/home/node/app
        environment:
            - DBWEBB_PORT_2=${DBWEBB_PORT_2}
            - DBWEBB_DSN=${DBWEBB_DSN}
        ports:
            - "${DBWEBB_PORT_2}:${DBWEBB_PORT_2}"
        links:
            - mongodb
        command: "npm start"

    realtime:
        image: skvist/docknode
        # build:
        #    context: .
        #    dockerfile: .docker/node-8.9/Dockerfile
        volumes:
            - ./services/realtime/:/home/node/app
        environment:
            - DBWEBB_PORT_3=${DBWEBB_PORT_3}
            - DBWEBB_DSN=${DBWEBB_DSN}
        ports:
            - "${DBWEBB_PORT_3}:${DBWEBB_PORT_3}"
        command: "npm start"

    mongodb:
        image: mongo:3.4
        environment:
            - MONGO_DATA_DIR=/data/db
        volumes:
            - ./data/db:/data/db
        ports:
            - ${DBWEBB_MONGO_PORT}:${DBWEBB_MONGO_PORT}
        command: mongod --port ${DBWEBB_MONGO_PORT}

    mongodb-test:
        image: mongo:3.4
        environment:
            - MONGO_DATA_DIR=/data/testdb
        volumes:
            - ./data/testdb:/data/testdb
        ports:
            - 3010:3010
        command: mongod --port 3010
    # webdev:
    #     build:
    #        context: .
    #        dockerfile: .docker/vue/Dockerfile
    #    ports:
    #        - "3000:8080"
    #    user: "node"
    #    working_dir: /home/node/app
    #    volumes:
    #        - ./services/web/:/home/node/app
    #    command: "node node_modules/.bin/webpack-dev-server --inline --progress --config build/webpack.dev.conf.js"

    webprod:
        image: nginx:stable-alpine
        volumes:
            - ./services/web/dist:/usr/share/nginx/html
        ports:
            - "${DBWEBB_PORT_0}:80"


    test1:
        build:
            context: .
            dockerfile: .docker/node-8.9/Dockerfile
        volumes:
            - ./:/home/node/app
        environment:
            - DBWEBB_PORT_1=${DBWEBB_PORT_1}
            - DBWEBB_DSN=mongodb://mongodb-test:3010/testkanban
        ports:
            - "${DBWEBB_PORT_1}:${DBWEBB_PORT_1}"
        links:
            - mongodb-test
        command: "npm run test-all-docker"

    test2:
        build:
            context: .
            dockerfile: .docker/node-6/Dockerfile
        volumes:
            - ./:/home/node/app
        environment:
            - DBWEBB_PORT_1=${DBWEBB_PORT_1}
            - DBWEBB_DSN=mongodb://mongodb-test:3010/testkanban
        ports:
            - "${DBWEBB_PORT_1}:${DBWEBB_PORT_1}"
        links:
            - mongodb-test
        command: "npm run test-all-docker"

    test3:
        build:
            context: .
            dockerfile: .docker/node-9/Dockerfile
        volumes:
            - ./:/home/node/app
        environment:
            - DBWEBB_PORT_1=${DBWEBB_PORT_1}
            - DBWEBB_DSN=mongodb://mongodb-test:3010/testkanban
        ports:
            - "${DBWEBB_PORT_1}:${DBWEBB_PORT_1}"
        links:
            - mongodb-test
        command: "npm run test-all-docker"