version: "3"
services:
    user:
        build:
            context: .
            dockerfile: .docker/node-8.9/Dockerfile
        volumes:
            - ./services/users/:/home/node/app
        environment:
            - DBWEBB_PORT_1=3001
            - DBWEBB_DSN=mongodb://mongodb:27018/users
        ports:
            - "3001:3001"
        links:
            - mongodb
        command: "npm run dev"

    kanban:
        build:
            context: .
            dockerfile: .docker/node-8.9/Dockerfile
        volumes:
            - ./services/kanban/:/home/node/app
        environment:
            - DBWEBB_PORT_2=3002
            - DBWEBB_DSN=mongodb://mongodb:27018/kanban
        ports:
            - "3002:3002"
        links:
            - mongodb
        command: "npm run dev"

    mongodb:
        image: mongo:3.4
        environment:
            - MONGO_DATA_DIR=/data/db
        volumes:
            - ./data/db:/data/db
        ports:
            - 27018:27018
        command: mongod --port 27018

    webdev:
        image: node:8.9-alpine
        ports:
            - "8090:8080"
        user: "node"
        working_dir: /home/node/app
        volumes:
            - ./services/web/:/home/node/app
        command: "npm run dev"

    webprod:
        image: nginx:stable-alpine
        volumes:
            - ./services/web/dist:/usr/share/nginx/html
        ports:
            - "8080:80"