
    webdev:
        image: node:8.9-alpine
        ports:
            - "3000:8080"
        user: "node"
        working_dir: /home/node/app
        volumes:
            - ./:/home/node/app
        command: "npm run dev"

    webprod:
        image: nginx:stable-alpine
        volumes:
            - ./services/web/dist:/usr/share/nginx/html
        ports:
            - "8080:80"
        command: "npm run build"